//@version=5
strategy("Viper", overlay=true)

/////////////////////////////////////////////////////////////////////////////////////////// Getting inputs///////////////////////////////////
//supertrend
atrPeriod = input(10, "ATR Length", group = "Supertrend")
factor = input.float(3.0, "Factor", step = 0.01, group ="Supertrend" )

//MACD
fast_length = input.int(title="Fast Length", defval=12,group ="MACD")
slow_length = input.int(title="Slow Length", defval=26,group ="MACD")
src = input.source(title="Source", defval=close,group ="MACD")
signal_length = input.int(title="Signal Smoothing",  minval = 1, maxval = 50, defval = 9,group ="MACD")
sma_source = input.string(title="Oscillator MA Type",  defval="EMA", options=["SMA", "EMA"],group ="MACD")
sma_signal = input.string(title="Signal Line MA Type", defval="EMA", options=["SMA", "EMA"],group ="MACD")
MACDResolution = input.string(title=' Resolution', defval='00 Current', options=['00 Current', '01 1m', '02 3m', '03 5m', '04 15m', '05 30m', '06 45m', '07 1h', '08 2h', '09 3h', '10 4h', '11 1D', '12 1W', '13 1M'], group = "MACD")


//2MA
MA1Period = input.int(21, title='MA1 Period', minval=1, step=1, group = "MA")
MA1Type = input.string(title='MA1 Type', defval='HMA', options=['RMA', 'SMA', 'EMA', 'WMA', 'HMA', 'DEMA', 'TEMA', 'VWMA'], group = "MA")
MA1Source = input.source(title='MA1 Source', defval=close, group = "MA")
MA1Resolution = input.string(title='MA1 Resolution', defval='00 Current', options=['00 Current', '01 1m', '02 3m', '03 5m', '04 15m', '05 30m', '06 45m', '07 1h', '08 2h', '09 3h', '10 4h', '11 1D', '12 1W', '13 1M'], group = "MA")
MA2Period = input.int(36, title='MA2 Period', minval=1, step=1, group = "MA")
MA2Type = input.string(title='MA2 Type', defval='HMA', options=['RMA', 'SMA', 'EMA', 'WMA', 'HMA', 'DEMA', 'TEMA', 'VWMA'], group = "MA")
MA2Source = input.source(title='MA2 Source', defval=close, group = "MA")
MA2Resolution = input.string(title='MA2 Resolution', defval='00 Current', options=['00 Current', '01 1m', '02 3m', '03 5m', '04 15m', '05 30m', '06 45m', '07 1h', '08 2h', '09 3h', '10 4h', '11 1D', '12 1W', '13 1M'], group = "MA")
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
ma(MAType, MASource, MAPeriod) =>
    if MAType == 'SMA'
        ta.sma(MASource, MAPeriod)
    else
        if MAType == 'EMA'
            ta.ema(MASource, MAPeriod)
        else
            if MAType == 'WMA'
                ta.wma(MASource, MAPeriod)
            else
                if MAType == 'RMA'
                    ta.rma(MASource, MAPeriod)
                else
                    if MAType == 'HMA'
                        ta.hma(MASource, MAPeriod)
                    else
                        if MAType == 'DEMA'
                            e = ta.ema(MASource, MAPeriod)
                            2 * e - ta.ema(e, MAPeriod)
                        else
                            if MAType == 'TEMA'
                                e = ta.ema(MASource, MAPeriod)
                                3 * (e - ta.ema(e, MAPeriod)) + ta.ema(ta.ema(e, MAPeriod), MAPeriod)
                            else
                                if MAType == 'VWMA'
                                    ta.vwma(MASource, MAPeriod)
res(Resolution) =>
    if Resolution == "00 Current"
        timeframe.period
    else
        if Resolution == "01 1m"
            "1"
        else
            if Resolution == "02 3m"
                "3"
            else
                if Resolution == "03 5m"
                    "5"
                else
                    if Resolution == "04 15m"
                        "15"
                    else
                        if Resolution == "05 30m"
                            "30"
                        else
                            if Resolution == "06 45m"
                                "45"
                            else
                                if Resolution == "07 1h"
                                    "60"
                                else
                                    if Resolution == "08 2h"
                                        "120"
                                    else
                                        if Resolution == "09 3h"
                                            "180"
                                        else
                                            if Resolution == "10 4h"
                                                "240"
                                            else
                                                if Resolution == "11 1D"
                                                    "1D"
                                                else
                                                    if Resolution == "12 1W"
                                                        "1W"
                                                    else
                                                        if Resolution == "13 1M"
                                                            "1M"
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
MA1 = request.security(syminfo.tickerid, res(MA1Resolution), ma(MA1Type, MA1Source, MA1Period))
MA2 = request.security(syminfo.tickerid, res(MA2Resolution), ma(MA2Type, MA2Source, MA2Period))
//MACD
fast_ma = request.security(syminfo.tickerid, res(MACDResolution), ma(sma_source, src, fast_length))
slow_ma = request.security(syminfo.tickerid, res(MACDResolution), ma(sma_source, src, slow_length))
macd = fast_ma - slow_ma
signal = sma_signal == "SMA" ? ta.sma(macd, signal_length) : ta.ema(macd, signal_length)

//supertrend
[supertrend, direction] = ta.supertrend(factor, atrPeriod)
upTrend = ta.change(direction) < 0 
downTrend = ta.change(direction) > 0
////////////////////////////////////////////////////////plot/////////////////////////////////////////////////////////////////////////////////
plot(MA1 , color=color.new(color.green, 0), linewidth=2, title='MA1')
plot(MA2 , color=color.new(color.purple, 0), linewidth=3, title='MA2')
plotshape(ta.cross(macd, signal), color= color.blue,style=shape.xcross,size=size.tiny, title="MACDCross")
plotshape(ta.cross(MA1, MA2), color= color.yellow,style=shape.xcross,size=size.tiny, title="MACross",location=location.belowbar)
//////strategy
macdcrossover = ta.crossover(macd, signal) 
macdcrossunder = ta.crossunder(macd, signal)
macrossover = ta.crossover(MA1,MA2)
macrossunder = ta.crossunder(MA1,MA2)

if macdcrossover and macrossover and upTrend
    strategy.entry("buy",strategy.long)
else
    if macdcrossunder    
        strategy.entry("sell",strategy.short)
    
if macdcrossunder and downTrend
    strategy.close("buy")
